version: "3.9"

services:
  app:
    build: .                     # Build from the optimized Dockerfile
    container_name: ecommerce_app
    ports:
      - "8080:80"                # App accessible on localhost:8080
    volumes:
      - .:/var/www/html           # Mount current folder into container
    depends_on:
      - db
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mini_ecommerce
      DB_USER: ecommerce_user
      DB_PASSWORD: ecommerce_pass

  db:
    image: mysql:8.0-oracle
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mini_ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: ecommerce_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ecommerce_user
      PMA_PASSWORD: ecommerce_pass
    depends_on:
      - db

volumes:
  db_data:
